#!/bin/bash

# ------------------------------------------------------ #
# if you add export PATH="/path/to/loganalyzer3:$PATH"
# you can use loganalyzer3 anywhere
#
# Examples of options
# debug mode: --debug
# dir mode: dirname -l
# file mode: filename --side l
#
# Examples of Execution
# loganalyzer3 /path/to/dir -l
# loganalyzer3 /path/to/file --side l --debug
# ------------------------------------------------------ #

echo "LogAnalyzer3"
echo "© 2018 Osaka Prefecture University Symbiotic Computing Lab."

DIR=`dirname $0`
if [ -d $1 ]; then
	${DIR}/loop.sh $*
else
	if [[ "$*" =~ --debug ]]; then
		opt=""
		while [ $# -gt 0 ]
		do
			case $1 in
				--debug)
					shift 1
					;;
				*)
					opt="${opt} ${1}"
					shift 1
					;;
			esac
		done
		python -O ${DIR}/main.py ${opt}
	else
		python ${DIR}/main.py $*
	fi
fi
